"""Schema shared by grounded context rendering and planner validation."""

REQUIRED_ACTION_ARGS = {
    "restart_screen_component": ("platform", "component", "screen_session", "project_root"),
    "start_screen_component": ("platform", "component", "screen_session", "project_root"),
    "stop_screen_component": ("screen_session",),
    "stop_platform_screens": ("platform",),
    "start_platform_screens": ("platform", "project_root"),
    "validate_project_files": ("project_root",),
    "prepare_project_files": ("project_root",),
    "extract_archive": ("archive_path", "destination_dir"),
    "run_install_script": ("script_dir", "script_name"),
    "ensure_shared_services": ("script_dir",),
    "write_ops_file": ("path", "content"),
    "replace_text_in_file": ("path", "old_text", "new_text"),
    "install_nginx_config": ("source_path", "config_name"),
    "start_docker_container": ("name",),
    "ensure_user_group": ("user", "group"),
    "remove_python_package_entries": ("site_packages_dir", "package", "entries"),
    "run_ops_command": ("program", "argv"),
    "copy_files": ("sources", "destination"),
    "move_path": ("source", "destination"),
    "create_directory": ("path",),
    "remove_path": ("path",),
    "manage_service": ("service", "operation"),
    "manage_process": ("pid", "signal"),
    "manage_container": ("name", "operation"),
    "install_system_packages": ("packages",),
    "install_python_packages": ("python_executable", "operation", "packages"),
    "manage_file_permissions": ("path",),
    "git_operation": ("operation", "repository"),
    "sync_directory": ("source", "destination"),
    "merge_json_file": ("path", "patch"),
    "start_redis_instance": ("binary", "config_path", "expected_port"),
    "run_reviewed_script": ("script_path", "cwd", "sha256"),
    "manage_libvirt_domain": ("domain", "operation"),
    "manage_docker_network": ("network", "operation"),
    "manage_docker_image": ("operation",),
    "manage_network_link": ("name", "operation"),
    "manage_ovs_resource": ("resource_type", "name", "operation"),
}
