sflow{
  collector { ip=172.17.0.127 udpport=6343 }
  agent = eth0
  polling = 10
  sampling = 10
  sampling.100M = 10
  sampling.1G = 10
  sampling.10G = 10
  sampling.40G = 10
  sampling.1T = 10
  tcp {}
}
